### ISSUE TITLE
Migrate tsconfig moduleResolution off deprecated 'node10' (TS 6.0)

### ISSUE THREAD

**Issue by yshrsmz** [AndroidDagashi/androiddagashi.github.io#626]
## Background

`typescript@6.0.3` (introduced in #616) deprecates `moduleResolution: "node"` (a.k.a. `node10`). `tsc` now emits:

> error TS5107: Option 'moduleResolution=node10' is deprecated and will stop functioning in TypeScript 7.0.

The option will be **removed in TypeScript 7.0**, so this needs to be cleaned up before the next major TS bump.

## Scope

The following 5 workspace packages all use the deprecated value in their `tsconfig.json`:

- `packages/site-common/tsconfig.json`
- `packages/site-api-github/tsconfig.json`
- `packages/site-api/tsconfig.json`
- `packages/site-config/tsconfig.json`
- `packages/site-rss/tsconfig.json`

(`packages/site` uses Nuxt's generated tsconfig with `moduleResolution: "Bundler"` already, so it's unaffected.)

## Why this is non-trivial

A naive `"node" → "node16"` / `"bundler"` swap surfaces several latent issues that the current loose `node10` resolution has been hiding. From an experimental attempt during #611 review:

- **TS1479**: `graphql-request`, `graphql-tag`, `cross-fetch` are ESM-only in their newest versions and can't be `require`'d from a `module: "commonjs"` package. Requires either `"type": "module"` + `.js` extensions in relative imports, or `.mts` files.
- **TS2550**: `Array.prototype.flatMap` is used in `src/mappers/*.ts` but `target: "es2018"` doesn't include it in the default lib. Needs `target` / `lib` bumped to `es2019`+.
- **TS2304** (under `bundler` resolution): `@graphql-tools/utils` typings reference `Disposable` / `AsyncDisposable` (`es2022.symbol`+). Need explicit `lib` extension.
- **TS2591** (under `bundler` resolution): `codegen.schema.ts` uses `process.env` but `@types/node` is no longer auto-included; needs explicit `"types": ["node"]`.
- **TS7006**: `noImplicitAny` catches `flatMap` callback parameters once the surrounding type errors clear.

## Constraints

- **Do NOT use `"ignoreDeprecations": "6.0"`** — it's a vendor escape hatch, not a fix. It also breaks again at TS 7.0.
- **Do NOT use `@ts-ignore` / `@ts-expect-error`** to silence the surfaced latent errors.
- Runtime entry points are executed via `tsx` (no `tsc` emit), so `module` / `target` choices only affect typechecking, not artifacts.

## Suggested approach

1. Bump `target` to `es2022` (or matching what Node 24 supports natively) and remove/expand `lib` accordingly.
2. Pick a `moduleResolution` per package — likely `node16` for script-style packages, with `module: "node16"` and `"type": "module"` in their `package.json`.
3. Add `.js` extensions to relative imports (codemod-friendly).
4. Verify each package with `yarn tsc --noEmit`, `yarn site:lint`, and an end-to-end `yarn api:generate` / `yarn rss:generate`.

## Related

- #611 — first surfaced this; chose to defer rather than expand scope. Two follow-up commits there are limited to codegen output regen and unused-dep cleanup.
- #616 — introduced TypeScript 6.0, which added the deprecation warning.
